## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "HIST099 Capstone: A Closer Look at Runaway Advertisements"
copyright = "{2023}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
googleAnalytics = "G-B7S6P11SZD"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A Closer Look at Runaway Advertisements"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  github = "https://github.com/theFestest/"
  twitter = "https://twitter.com/caressofsteel_"
  email = "mwb70@georgetown.edu"
  instagram = "https://instagram.com"
  linkedin = "https://linkedin.com"
  telegram = "https://telegram.org"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]